### ISSUE TITLE
 How to process the Multilevel Modeling (MLM) ?

### ISSUE THREAD

**Issue by 672234993** [LiveOak/sheik-microbial-grassland-warming-1#1]
Hi, 
I am intersted in the MLM you applied to control for spatial variation in microbial population response at the sampling site. But I can hardly repeat MLM by myself now. With which program you used or Could you please make the code you applied publicly availale? Which will make a big step forward for making reproducible research.
Any reply is helpful, Many thanks!

**Comment by wibeasley** [comment]
Hi @672234993, thanks for your interest.

The Bayesian MLM that you’re most interested is in https://github.com/LiveOak/sheik-microbial-grassland-warming-1/blob/master/analysis/model/model.txt.  This was WinBUGS (called from R), but I just converted things to OpenBUGS ([called from R](https://github.com/LiveOak/sheik-microbial-grassland-warming-1/blob/master/analysis/model/model.R)), because it's [replacing WinBUGS](http://www.openbugs.net/w/FrontPage).

Because the matched plots were so close together, and the nonmatched plots were so far, there wouldn’t have been a benefit of using spatial modeling in the Brad Carlin sense (http://www.biostat.umn.edu/~brad/; but I loved his spatial book almost as much as his general Bayesian book).  In a sense, we controlled for the spatial variability with the design instead of statistics.  With 5 “plots” (each containing a normal and a warmed patch), I don’t think Carlin-esque spatial models could even converge.  Spatial location was indicated with a (fixed) categorical Level 2 intercept; see subscript `j` in the bugs file I linked above.  

That’s my memory of the situation anyway.  I believe I've answered your question.  Please reopen the issue if not.  If you have another question, feel free to open another issue like you did.  -Will

``` r
for( j in 1:plotCount ) {
  b0[j]  ~ dnorm(0, tau.b0)
  b0.adj[j] <- b0[j] - mean(b0[ ])
}
```
